// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StromAPI.Models;

#nullable disable

namespace StromAPI.Migrations.MagazineStockDbMigrations
{
    [DbContext(typeof(MagazineStockDb))]
    [Migration("20230831114420_NewDb")]
    partial class NewDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("StromAPI.Models.MagazineStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Area")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Capacity")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<double>("Filling")
                        .HasColumnType("REAL");

                    b.Property<double>("FillingFactor")
                        .HasColumnType("REAL");

                    b.Property<double>("FillingFactorChange")
                        .HasColumnType("REAL");

                    b.Property<double>("FillingFactorLastWeek")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MagazineStocks");
                });
#pragma warning restore 612, 618
        }
    }
}
